### PR TITLE
Adding Jul 2023 Digest

### PR DESCRIPTION
**Pull request by RickTanWY**

### CODE REVIEW

**Comment by RickTanWY** [comment]
Added Info and Cyber reports for July

**Comment by wchiongh** [comment]
Approved pull request to upload Jul reports.

**Review by wchiongh — COMMENTED** [review]
Approved

**Review by wchiongh — APPROVED** [review]

**Comment by wchiongh** [comment]
Approved pull request to load Jul 2023 reports onto website

**Pull request merged**
